elecshop/admin/routes.py
from flask import render_template, redirect, url_for, request, flash, Blueprint
from flask_login import login_required, current_user
from elecshop import db
from elecshop.models import User, Products, Types
from elecshop.admin.forms import (
    AddProductTypeForm,
    EditProductTypeForm,
    AddProductForm,
    EditProductForm,
)
from elecshop.admin.utils import (
    save_picture,
    get_product_type_id,
    get_product_type,
    get_product,
)

admin = Blueprint("admin", __name__)


"""
=====================================================================================================================================================================
PRODUCTS
=====================================================================================================================================================================
"""


@login_required
@admin.route("/products", methods=["GET", "POST"])
def products():
    if current_user.user_name == "Admin":
        page = request.args.get("page", 1, type=int)
        products = Products.query.paginate(page=page, per_page=5)
        return render_template(
            "admin/products.html", title="All Products", products=products
        )
    return render_template("404.html")


@login_required
@admin.route("/products/<product_id>", methods=["GET", "POST"])
def product_item(product_id):
    if current_user.user_name == "Admin":
        page = request.args.get("page", 1, type=int)
        users = User.query.paginate(page=page, per_page=5)
        return render_template(
            "admin/product_item.html", title="Product Details", users=users
        )
    return render_template("404.html")


@login_required
@admin.route("/products/add_product", methods=["GET", "POST"])
def add_product():
    if current_user.user_name == "Admin":
        form = AddProductForm()
        if form.validate_on_submit():
            product_type = (form.product_type.data).product_type
            if form.picture.data:
                picture_file = save_picture(form.picture.data, "Product")
                product = Products(
                    product_name=form.productname.data,
                    price=form.price.data,
                    quantity=form.quantity.data,
                    availablity=form.availablity.data,
                    image_file=picture_file,
                    details=form.details.data,
                    product_type=get_product_type_id(product_type),
                )
            else:
                product = Products(
                    product_name=form.productname.data,
                    price=form.price.data,
                    quantity=form.quantity.data,
                    availablity=form.availablity.data,
                    details=form.details.data,
                    product_type=get_product_type_id(product_type),
                )
            db.session.add(product)
            db.session.commit()
            flash(f"Product Added Successfully", "success")
            return redirect(url_for("admin.products"))
        return render_template(
            "admin/add_product.html",
            title="Add Product",
            form=form,
            legend="Add Product",
        )
    return render_template("404.html")


@login_required
@admin.route("/products/<product_id>/edit_product", methods=["GET", "POST"])
def edit_product(product_id):
    if current_user.user_name == "Admin":
        form = EditProductForm()
        product = get_product(product_id)
        if form.validate_on_submit():
            if form.picture.data:
                picture_file = save_picture(form.picture.data, "Product")
                product.image_file = picture_file
            product_type = (form.product_type.data).product_type
            product.product_name = form.productname.data
            product.price = form.price.data
            product.quantity = form.quantity.data
            product.availablity = form.availablity.data
            product.details = form.details.data
            product.product_type = get_product_type_id(product_type)
            db.session.commit()
            flash(f"Product Updated Successfully", "success")
            return redirect(url_for("admin.products"))
        elif request.method == "GET":
            product_type = get_product_type(product.product_type)

            form.picture.data = product.image_file
            form.productname.data = product.product_name
            form.price.data = product.price
            form.quantity.data = product.quantity
            form.availablity.data = product.availablity
            form.details.data = product.details
            form.product_type.data = product.product_type
        image_file = url_for("static", filename="products_pics/" + product.image_file)
        return render_template(
            "admin/edit_product.html",
            title="Update Product",
            form=form,
            legend="Edit Product",
            image_file=image_file,
        )
    return render_template("404.html")


@login_required
@admin.route("/produts/<product_id>/delete_product", methods=["GET", "POST"])
def delete_product(product_id):
    if current_user.user_name == "Admin":
        product = get_product(product_id)
        db.session.delete(product)
        db.session.commit()
        flash(f"Product  Deleted Successfully", "danger")
        return redirect(url_for("admin.products"))
    return render_template("404.html")


"""
=====================================================================================================================================================================
PRODUCT TYPE
=====================================================================================================================================================================
"""


@login_required
@admin.route("/product_type", methods=["GET", "POST"])
def product_type():
    if current_user.user_name == "Admin":
        page = request.args.get("page", 1, type=int)
        types = Types.query.paginate(page=page, per_page=5)
        return render_template(
            "admin/product_type.html", title="Product Type", types=types
        )
    return render_template("404.html")


@login_required
@admin.route("/product_type/new", methods=["GET", "POST"])
def add_product_type():
    if current_user.user_name == "Admin":
        form = AddProductTypeForm()
        if form.validate_on_submit():
            type = Types(product_type=form.product_type_name.data)
            db.session.add(type)
            db.session.commit()
            flash(f"Product Type Added Successfully", "success")
            return redirect(url_for("admin.product_type"))
        return render_template(
            "admin/add_product_type.html",
            title="Adding Product Type",
            form=form,
            legend="New Product Type",
        )
    return render_template("404.html")


@login_required
@admin.route("/product_type/<type_id>/edit_product_type", methods=["GET", "POST"])
def edit_product_type(type_id):
    if current_user.user_name == "Admin":
        form = EditProductTypeForm()
        type = get_product_type(type_id)
        if form.validate_on_submit():

            type.product_type = form.product_type_name.data
            db.session.commit()
            flash(f"Product Type Updated Successfully", "success")
            return redirect(url_for("admin.product_type"))
        elif request.method == "GET":
            form.product_type_name.data = type.product_type
        return render_template(
            "admin/add_product_type.html",
            title="Adding Product Type",
            form=form,
            legend="Edit Product Type",
        )
    return render_template("404.html")


@admin.route("/product_type/<type_id>/delete_type", methods=["GET", "POST"])
@login_required
def delete_type(type_id):
    type = get_product_type(type_id)
    if current_user.user_name == "Admin":
        db.session.delete(type)
        db.session.commit()
        flash(f"Product Type Deleted Successfully", "danger")
        return redirect(url_for("admin.product_type"))
    return render_template("404.html")


"""
=====================================================================================================================================================================
CUSTOMERS
=====================================================================================================================================================================
"""


@login_required
@admin.route("/customers", methods=["GET", "POST"])
def customers():
    if current_user.user_name == "Admin":
        page = request.args.get("page", 1, type=int)
        users = User.query.paginate(page=page, per_page=5)
        return render_template(
            "admin/customers.html", title="Customer Details", users=users
        )
    return render_template("404.html")

elecshop/shop/routes.py
from flask import render_template, request, Blueprint
from elecshop import db
from elecshop.models import Products

shop = Blueprint("shop", __name__)


@shop.route("/")
@shop.route("/home")
def home():
    page = request.args.get("page", 1, type=int)
    products = Products.query.paginate(page=page, per_page=5)
    # products= Products.query.all()

    return render_template("/home.html", title="Dashboard", products=products)

elecshop/users/routes.py
from elecshop import db, bcrypt
from flask import render_template, url_for, flash, redirect, request, Blueprint
from elecshop.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm,
)
from elecshop.users.utils import save_picture, send_reset_email
from elecshop.models import User
from flask_login import login_user, current_user, logout_user, login_required


users = Blueprint("users", __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("shop.home"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user = User(
            user_name=form.username.data,
            first_name=form.firstname.data,
            last_name=form.lastname.data,
            contact_num=form.phone.data,
            email=form.email.data,
            password=hashed_password,
        )
        db.session.add(user)
        db.session.commit()

        flash(f"Account Created For {form.firstname.data} !", "success")
        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("shop.home"))

    form = LoginForm()
    if form.validate_on_submit():
        # user_1 = User.query.filter_by(user_name = form.uname_email_phone.data).first()
        # user_2 = User.query.filter_by(email = form.uname_email_phone.data).first()
        # user_3 = User.query.filter_by(contact_num = form.uname_email_phone.data).first()
        # user = next(usr for usr in [user_1, user_2, user_3] if usr)
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            flash(f"You have been logged in: {user.user_name} !", "success")
            return redirect(url_for("shop.home"))
        else:
            flash(f"Login Unsuccessful!", "danger")
    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("shop.home"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.user_name = form.username.data
        current_user.first_name = form.firstname.data
        current_user.last_name = form.lastname.data
        current_user.email = form.email.data
        db.session.commit()
        flash(f"Account Updated Successfully", "success")
        return redirect(url_for("users.account"))
    elif request.method == "GET":
        form.username.data = current_user.user_name
        form.firstname.data = current_user.first_name
        form.lastname.data = current_user.last_name
        form.email.data = current_user.email

    image_file = url_for("static", filename="profile_pics/" + current_user.image_file)
    return render_template(
        "account.html", title="Account", image_file=image_file, form=form
    )


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for("shop.home"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("Email with reset password link has been sent.", "success")
        return redirect(url_for("users.login"))
    return render_template(
        "reset_request.html", title="Request Reset Password", form=form
    )


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for("shop.home"))

    user = User.verify_reset_token(token)
    if user is None:
        flash("Invalid or Expire Token", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode(
            "utf-8"
        )
        user.password = hashed_password
        db.session.commit()
        flash(f"Your password has been updated!", "success")
        return redirect(url_for("users.login"))
    return render_template("reset_token.html", title="Reset Password", form=form)

elecshop/templates/admin.html
{% extends "nav.html" %}
{% block content %}



      
    
<div class="container justify-content-md-center">
  <div class="row justify-content-md-center">
    <div>
      
    </div>
    <!-- <div class="col-4 dropdown ">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Products
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><a class="dropdown-item" href="{{ url_for('admin.add_product') }}">Add Product</a></li>
        <li><a class="dropdown-item" href="{{ url_for('admin.edit_product') }}">Edit Product</a></li>
        <li><a class="dropdown-item" href="{{ url_for('admin.delete_product') }}">Delete Product</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="{{ url_for('admin.all_products') }}">Products</a></li>
      </ul>
    </div>
               
    <div class="col-4 dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Product Type
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><a class="dropdown-item" href="#">Add Product Type</a></li>
        <li><a class="dropdown-item" href="#">Edit Product Type</a></li>
        <li><a class="dropdown-item" href="#">Delete Product Type</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Product Types</a></li>
      </ul>
    </div>
    
    <div class="col-4 dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Customer
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        <li><a class="dropdown-item" href="#">Add Customer</a></li>
        <li><a class="dropdown-item" href="#">Edit Customer</a></li>
        <li><a class="dropdown-item" href="#">Delete Customer</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Customers</a></li>
      </ul>
    </div> -->
  </div>
</div>





{% endblock content %}

elecshop/templates/home.html
{% extends "nav.html" %}
{% block content %}







    <div class="container">
        <div class="row">
            {% for product in products.items %}
            <div class="col-md-4 mt-3">
                <div class="card" >
                    <img src="{{ url_for('static', filename='products_pics/' + product.image_file) }}" alt="{{ product.product_name}}" class="card-img-top" height="200">
                    <div class="card-body">
                        <h5 class="text-center">{{ product.product_name }}</h5>
                        <p class="text-center"><span style="white-space: nowrap;"><i class="fa fa-inr">&nbsp;</i>{{  "%.2f"|format(product.price) }}</span></p>
                    </div>
                    <div class="card-footer" >
                        <button href="#" id="example" class="float-left btn btn-sm btn-primary" data-bs-toggle="popover" title="Specifications" data-bs-content="And here's some amazing content. It's very engaging. Right?">Specs</button> <button href="#" class="float-right btn btn-sm btn-warning">Add to cart</button>
                    </div>

                </div>

            </div>
            {% endfor %}
            <div class="container mt-4 ">
            {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    <div class="justify-content-center"> 
                        {% if products.page == page_num%}
                        <a class="btn btn-info mb-4" href="{{ url_for('shop.home', page= page_num) }}">{{ page_num }}</a>
                        {% else %}
                        <a class="btn btn-outline-info mb-4" href="{{ url_for('shop.home', page= page_num) }}">{{ page_num }}</a>
                        {% endif %}
                    </div>
                {% else %}
                ...
                {% endif %}
            {% endfor %}
        </div>
        </div>

    </div>


{% endblock content %}

{% block script %}
<script>
var popoverTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="popover"]'))
var popoverList = popoverTriggerList.map(function (popoverTriggerEl) {
  return new bootstrap.Popover(popoverTriggerEl)
})
</script>
{% endblock %}

elecshop/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title> My Electrical Shop - {{ title }}</title>
    {% else %}
        <title> My Electrical Shop </title>
    {% endif %}
</head>
<body>
    <ul class="nav justify-content-end ">
        {% if current_user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link active"  href="{{ url_for('users.account') }}">Account</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active"  href="{{ url_for('users.logout') }}">Log Out</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link active"  href="{{ url_for('users.login') }}">Sign In</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{{ url_for('users.register') }}">Register</a>
        </li>
        {% endif %}    
    </ul>
   
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel ">
            <div class="container">
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div>
                <ul class="navbar-nav justify-content-end ">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active"  href="{{ url_for('users.account') }}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active"  href="{{ url_for('users.logout') }}">Log Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active"  href="{{ url_for('users.login') }}">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('users.register') }}">Register</a>
                    </li>
                    {% endif %}                
                </ul>
            </div>
            </div>
        </nav>
    </header>
</body>
    <main role="main" class="container">
        <div class="row">
        <div class="col-md-8"> 
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
            
        </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</html>

elecshop/templates/login.html
{% extends "nav.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom, mb-4"> Log In</legend>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}

<!--                     {{ form.email(class="form-control form-control-lg") }} -->
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input")}}
                    {{ form.remember.label(class="form-check-label")}}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>
            <small class="text-muted ml-2">
                <a href="{{url_for('users.reset_request')}}">Forgot Password?</a>
            </small>
        </form>        
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Don't Have An Account? <a class="ml-2" href="{{ url_for('users.register') }}"> Register Here</a>
        </small>
        
    </div>
{% endblock content%}

elecshop/templates/nav.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
<!--     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <script src="https://kit.fontawesome.com/307bee2982.js" crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> -->
    <script src="extensions/resizable/bootstrap-table-resizable.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    {% if title %}
        <title>My Elec Shop - {{ title }}</title>
    {% else %}
        <title>My Elec Shop</title>
    {% endif %}
</head>
<body>
    <body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">My Elec Shop</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample01" aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <!-- <a class="nav-item nav-link" href="{{ url_for('shop.home') }}">Home</a> -->
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <h6 class="nav-item nav-link">Hi {{ current_user.first_name }}!</h6>
                {% if current_user.user_name == 'Admin' %}
                  <!-- <a class="nav-item nav-link" href="#">Admin</a> -->
                  <a class="nav-item nav-link" href="{{ url_for('admin.products') }}">Products</a>
                  <a class="nav-item nav-link" href="{{ url_for('admin.customers') }}">Customer</a>
                  <a class="nav-item nav-link" href="{{ url_for('admin.product_type') }}">Product Type</a>
                {% endif %}
                {% if current_user.user_name != 'Admin' %}
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}"><i class="fa fa-shopping-cart" data-toggle="tooltip" data-placement="top" title="Cart"></i></a>
                {% endif %}
                
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}"><i class="fa fa-user" data-toggle="tooltip" data-placement="top" title="My Account"></i></a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}" ><i class="fa fa-sign-out" data-toggle="tooltip" data-placement="top" title="Sign Out"></i></a>
                
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8"> 
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
            
        </div>
    </main>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS --> 
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script> -->
    <script src="extensions/resizable/bootstrap-table-resizable.js"></script>
</body>
</html>